name: get-chat-ids

on:
  workflow_dispatch:

jobs:
  ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install requests feedparser

      - name: Show chat ids
        env:
          RUBIKA_TOKEN: ${{ secrets.RUBIKA_TOKEN }}
        run: python main.py ids
